trigger:
  branches:
    include:
      - main

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: MavenAuthenticate@0
    inputs:
      mavenCredentials: 'MavenCredentials'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests'

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      containerRegistry: 'Docker-Hub-Connection'
      repository: 'shivakrishna99/az-Shopping-Cart'
      dockerfile: '**/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        latest
        $(Build.BuildId)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: 'push'
      containerRegistry: 'Docker-Hub-Connection'
      repository: 'shivakrishna99/Shopping-Cart'
      tags: |
        latest
        $(Build.BuildId)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/target'
      ArtifactName: 'Shopping-Cart'
